### ISSUE TITLE
`diadon setup` fails with error

### ISSUE THREAD

**Issue by Flashwalker** [f-person/diadon#2]
`diadon setup` fails with:
```
Traceback (most recent call last):
  File "/home/user/bin/diadon", line 210, in <module>
    configs = read_configurations()
  File "/home/user/bin/diadon", line 89, in read_configurations
    with open(config_file_path, 'r') as configs_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/diadon/keys.json'
```

**Comment by f-person** [comment]
Hi! This is a pretty old script, and I guess there's some misinformation in the README (or the script is working incorrectly). I'll try to fix the errors soon. Meanwhile, if you want, you can manually set it up by editing the `~/.config/diadon/keys.json` file with the following data:

```json
{
    "diaspora": {
        "pod_url": "",
        "username": "",
        "password": ""
    },
    "mastodon": {
        "instance_url": "",
        "client_id": "",
        "client_secret": "",
        "access_token": ""
    },
    "mastodon_max": 500
}
```
